name: hello-runner

on: [push]

jobs:
  on-windows:
    runs-on: windows-latest
    steps:
      - run: Get-ComputerInfo | Select-Object OsName, OsVersion

  on-mac:
    runs-on: macos-latest
    steps: 
      - run: sw_vers